services:
  mt5:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mt5
    ports:
      - 3000:3000
      - 8001:8001
    networks:
      - homelabs

networks:
  homelabs:
    external: true